######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 14 09:45:54 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug
# Input
HEADERS += form2048.h
SOURCES += form2048.cpp main.cpp
